### ISSUE TITLE
Japanese manga style controls

### ISSUE THREAD

**Issue by sadmir** [nkanaev/bubble#10]
Right-to-left reading option (touching the left side of the screen to go the next page and the right to go back a page) and also 7z support.

**Comment by Desolutional** [comment]
I second this (essentially Manga, Japanese reading format). Maybe assign a menu option which when activated, swaps the left and right page controls around.

**Comment by sadmir** [comment]
It was feature request because I was also requesting 7z support I guess but I like your title better.

**Comment by Desolutional** [comment]
7z support is quite tricky to implement from what I've been reading online, but maybe nkanaev may have better luck? So far I've seen the official 7-Zip SDK and also the binding library "sevenzipjbind".

**Comment by prysme01** [comment]
Hello all I would like to see the manga style too. It would be great for manga readers.

**Comment by nkanaev** [comment]
Implemented in v1.3.0. Left-to-right & right-to-left reading option can be switched in reading mode.

**Comment by nkanaev** [comment]
As of 7z support, I think it is better to create another ticket for the feature. I would be glad if someone could provide me some content to experiment with, since I don't have 7z archived comics and couldn't find any in the "wild"

**Comment by prysme01** [comment]
Hello, the option are ok but when you choose right to left, the click action is not reverse. click on the  right part go one page right. Changing orientation should also include reversing control.

**Comment by nkanaev** [comment]
@prysme01 sorry I didn't understand what you've meant, but right-to-left reading mode reverses reading controls - sliding right will switch to the previous page (just like clicking right edge).

**Comment by prysme01** [comment]
I'm used to use Comicrack and Right to left navigation mode is not correlated with the page sliding orientation. So when reading mode is set to Manga, the control are not flipped, right clicking is still going forward. And CR offers a way to redefine the clicking zones action among a set of command.

I would suggest that we can redefine the behavior of the right /left click  (forward or backward) and still be able to choose Right to Left or Left to Right mode to define how the images are going to slide..

**Comment by nkanaev** [comment]
sorry, the new click navigation is unlikely to change. and I generally dislike settings pages, as they increase development & using complexity. most of the users don't change the settings btw, except for some critical parts, which are already present in navigation bar.

**Comment by prysme01** [comment]
I understand your standpoint, maybe I'm wrong, I'm an european "reader" use to read from front to back and I also read Japanese book made to be read from back to front. 
Furthermore, I'm right handed in a country that write from left to right --> for me right means forward. 
People are left-handed and lives in country that wrote from right to left.
I agree with you about complexity, but defining if the right click should go next or previous could be help, even if this is not critical.

Anyway I dont want to bother you anymore on this as the main feature is present (back to front reading mode for manga)
