### ISSUE TITLE
Automatic zoom/fit to width

### ISSUE THREAD

**Issue by mkaito** [nkanaev/bubble#11]
I know it says optimized for tablets, but I like reading manga on my phone while commuting/idling. Since the phone is too small to read manga in portrait, I like to flip it over, fit pages to width, and scroll with my finger as I read.

There's a number of things that you could do about it, none of which are necessarily mutually exclusive:

* Default to fit-to-width in landscape orientation (or add an option to mark preferred zoom mode)
* Double tap to zoom in, or switch between fit-to-width/height and fit-whole-page zoom modes.
* Remember zoom from last page

**Comment by mkaito** [comment]
Nevermind. Seems to be already there.

The zoom option button gets lost under the navigation buttons in landscape, though, which is why I didn't notice it.

**Comment by prysme01** [comment]
Mkaito , where is the remember zoom from last page option, I can't see it, it could be very usefull.
On 1.3.0 I only have 3 options, and neither of the three are preserving the zoom from last page.

**Comment by mkaito** [comment]
I don't think there's such a thing. It was just a proposal for what I thought was a missing feature. You can select the zoom mode in the upper right corner after tapping the middle of the screen when reading a comic.

**Comment by prysme01** [comment]
If you don't mind I will create a feature request, Maybe my dream could come true :)
Anyway Mkaito, thank you for this application, and even if you don't want to spend time on such request, maybe I will  kick my ass and learn how to make it myself to contribute :)

**Comment by mkaito** [comment]
I'm not the author. That's @nkanaev.
