### ISSUE TITLE
[Feature Request] 7z support

### ISSUE THREAD

**Issue by sadmir** [nkanaev/bubble#13]
New ticket for the 7z support.
>I would be glad if someone could provide me some content to experiment with, since I don't have 7z archived comics and couldn't find any in the "wild"
https://mega.nz/#!alpzAZQI!W8bnccwGMztyqxwCxaKxN5-9QnqlWhIflxPKNaKOAJ4
https://drive.google.com/file/d/0B8qZl1E-YL67aDdoQlQ4cDRGbm8/
It's just regular images inside a 7zip archive.

If 7zip support is as hard as others were saying you really shouldn't waste your time on this. 
Like you said 7z comics or manga are rare and you could just extract them and archive them as zip/rar when you find them.

**Comment by nkanaev** [comment]
the feature will land in the next release
