### ISSUE TITLE
[Feature Request] Register as CBZ application

### ISSUE THREAD

**Issue by prysme01** [nkanaev/bubble#14]
My comic/manga are located on a server, I mainly use ES explorer to acces my share drive.
It would be convenient if Bubble could be registered to open CBZ file.
As I see with es explorer when clicking on a cbz file it does not offer to open with Bubble.

it seems that Bubble is not registered as a application that is able to open certain type of file.

**Comment by nkanaev** [comment]
implemented in v1.4.0
