### ISSUE TITLE
[Feature Request] Resume reading

### ISSUE THREAD

**Issue by prysme01** [nkanaev/bubble#16]
Would it be possible to add somewhere an button to resume reading the last reading book ?

**Comment by nkanaev** [comment]
I am thinking about adding a new menu or "Currently reading" virtual folder like @IceHand84 suggested. The feature should make easier reading experience by not forcing to remember last page/comic read last time. Currently I am open to new suggestions as I don't have an established idea how to implement it yet.

**Comment by mkaito** [comment]
Well, abstractly speaking it should remember the last seen page in the latest opened chapter for each manga/comic that you're reading. That, however, requires defining the concepts of "comic" and "chapter".

**Comment by nkanaev** [comment]
By comic I was referring to a single file (I guess you meant "chapter" by it).

**Comment by prysme01** [comment]
Virtual view would be nice. Maybe with the possibility to be filter (started, not started, recently added)

**Comment by mkaito** [comment]
The way I organize my manga is by keeping each chapter or volume in its own cbz file, all within a folder for the manga, sequentially numbered. If you assume a similar structure, keeping a cache of recently viewed chapters/pages would be trivial.

**Comment by IceHand84** [comment]
How about a "Continue reading" view, where from each folder the last opened file that has the status "currently reading" is shown -- sorted by last opened date. 

Or you could add a "continue reading" button to each folder in library view that opens the last opened file.

**Comment by droidberg** [comment]
i have also wanted to this feature. it would come in handy when reading trade paperbacks. so, how about implementing it in the left panel upper window, the one that shows comicbook covers. the following image shows what im talking about:

http://i.imgur.com/hUHWhaB.jpg

anyway, Astonishing Comic Reader does this. its very useful and i think it would be great if you incorporated it into bubble. heres a view of how it looks on astonishing:

http://i.imgur.com/ZJJPgqq.jpg

**Comment by nkanaev** [comment]
Ok, sorry for the late reply. I've come up with an idea of storing reading history. Now when you start reading "chapter" inside "comic" series, the recent ones (currently 5) will show up on the top of the list. This way you may remember which ones you've read last. The feature is available since v1.5.0
