### ISSUE TITLE
Can't read external sd card

### ISSUE THREAD

**Issue by IceHand84** [nkanaev/bubble#2]
I have installed Bubble 1.0.2 from F-Droid and like it very much. Unfortunately I can't access the external sd card. It simply isn't possible to choose anything other than /storage/emulated/0

I have a Samsung Galaxy Tab Pro 10.1 and I'm using Cyanogenmod 12.

**Comment by nkanaev** [comment]
Thanks for the feedback. Seems like you have more than 1 external storage directories. Will add support for multiple directories soon.

**Comment by LOLLeela** [comment]
Awesome,

I just grabbed this as well, i am on a sony z2 tab and have the same issue.

On my device they mount as

/storage/sdcard0 - internal 16gb "sdcard"/storage
/storage/sdcard1 - sdcard
/storage/usbdisk - usb disk

**Comment by LOLLeela** [comment]
I'm no android dev, but looks like you can check for this with a public static boolean "isExternalStorageEmulated"

It should return true if the "ExternalStorage" is internal like on my devices.

Here is an example using "System.getenv("SECONDARY_STORAGE")" to find the external sdcard.
https://github.com/shivarajp/AndroidDirectoryChooserExample

Sorry if this is no help.

**Comment by RyDroid** [comment]
I have the same issue. Just allow "..." to go to sub-directories, of course except at the root of the file system.

**Comment by nkanaev** [comment]
OK, I decided not to overthink the issue, and did as @RyDroid suggested. v1.1.0 now supports browsing whole filesystem.

**Comment by RyDroid** [comment]
Great, it works perfectly for me.

**Comment by LOLLeela** [comment]
Works great for me, thanks!

**Comment by IceHand84** [comment]
Thank you, this fixes the issue.
