### ISSUE TITLE
Problem with some comic book archives, which do not have the picture files in the root folder

### ISSUE THREAD

**Issue by countsudoku** [nkanaev/bubble#21]
I have some comic (cbr) archives, which have all the page pictures in a subfolder. If I'm opening such a file, first it will be rendered good and you can go from the first page to the next and so on with no problem. But if you skip some pages, or if you close the app and try later to resume you get only a gry page with a "broken page" symbol (see attachment)
![screenshot_bubble_subfolder-problem2](https://cloud.githubusercontent.com/assets/8734751/10290820/986b4298-6ba6-11e5-86f0-854d9d8ddaef.png)

.
If chekt the difference betwen archive, that have the problem and archives which don't. The only difference I found, was that the pictures of the book pages were in a subfolder. Then I repacked the archive with no subfolder and the problem vanished.
I've tested this only with CBRs, because I do not use other comic book archives. Perhaps this issue occurs also with other formats.

**Comment by nkanaev** [comment]
@countsudoku is the issue still present in v1.4.0? if yes, could you send me a file which fails to open properly?

**Comment by countsudoku** [comment]
I still have some problems with some CBR files. But I didi some research, whats causing the problems. I tried to create some CBR files which do have the same issue, but I were not able to do that.

Then I tried to unpack the archive and then packed it again. After this procedure the archive doen't have any problems in Bubble at all. The orginal archive was packed with a windows rar tool and I repacked it with the Linux rar command. So I think the original file was perhaps badly packed.

**Comment by nkanaev** [comment]
If the issue is still present, could you send me couple of windows-packed files for some investigation? my e-mail is nkanaev [at] live [dot] com

**Comment by nkanaev** [comment]
ok, i've done some research, and seems that the issue causing broken images is related to [solid archives](https://en.wikipedia.org/wiki/Solid_compression).
I've submitted patch to fix the issue, but opening solid archives might take longer time than usual (depends on device)

**Comment by nkanaev** [comment]
Attaching sample file in just in case
[BARKS_LIBRARY_-_DAISY_DUCK_001__D_.cbr.zip](https://github.com/nkanaev/bubble/files/200894/BARKS_LIBRARY_-_DAISY_DUCK_001__D_.cbr.zip)
