### ISSUE TITLE
No images on cards, v1.3.0

### ISSUE THREAD

**Issue by x2k13** [nkanaev/bubble#23]
- Honor 6, Android Lollipop 5.1.1, EMUI 3.1
- Clean install of Bubble v1.3.0 via F-Droid app

No cover/preview images are shown on any cards of the library or inside collections (see screenshots below).

![screenshot_1](https://cloud.githubusercontent.com/assets/13673423/11625635/a9c32666-9cdc-11e5-88a7-1da7bc20e9c9.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/13673423/11625637/add1ef76-9cdc-11e5-8276-260b79dda895.png)

**Comment by nkanaev** [comment]
hi, @x2k13. do files still open?

**Comment by x2k13** [comment]
Yes, files still open flawlessly.

**Comment by nkanaev** [comment]
ok, this might seem dumb, but have you tried restarting your phone? i used to have this issue while developing the app, and the only solution was to restart android. couldn't figure out the reason though.

**Comment by x2k13** [comment]
Restarted my phone just to be sure, but unfortuately no luck. Refreshing the library and/or resetting the file directory path didn't help either. Hmmm

**Comment by x2k13** [comment]
I wondered, might this issue be related to [issue #18](https://github.com/nkanaev/bubble/issues/18) by any chance?

**Comment by x2k13** [comment]
Fixed in version 1.4.0
Thank you @nkanaev!
Closed.
