### ISSUE TITLE
Library does not adhere to directory structure

### ISSUE THREAD

**Issue by Sylphychan** [nkanaev/bubble#24]
Here is an example of my directory structure
```
|---Comics
     |--Superman
     |   |---Superman #001.cbz
     |   |---Misc
     |       |---Convergence: Superman #001.cbz
     |--Wonder Woman
         |---Wonder Woman #001.cbz
         |---Misc
             |---Wonder Woman: Futures End #001.cbz
```
The cards displayed on the library home are Superman, Wonder Woman, and both Misc folders. It shouldn't show the Misc folders until you've descended into its parent.

**Comment by nkanaev** [comment]
@Sylphychan, thanks for the feedback. My idea of the app was to have a library management without deep nesting (like Komik Reader) and the need to regroup/reorganize the library. 

However, I get your point. Some users might have "special/misc/additional" subfolders, which might be confusing. I can change the representation to show parent folder name (if it contains comics as well), so instead of: 

    Superman
    Misc
    Wonder Woman
    Misc

the library will show:

    Superman
    Superman | Misc
    Wonder Woman
    Wonder Woman | Misc

**Comment by Sylphychan** [comment]
So long as they always come after their parent and are in order then that would be a great solution.

Example:
```
Superman
Superman | Arc 001
Superman | Arc 002
Superman | Misc
```

**Comment by droidberg** [comment]
so far the app that does the best job of handleing my comicbook library is Pow! comic reader. it shows my library the exact way i have it on my sd card.

[ComicBook Library]
	Black Jack Ketchum
		Black Jack Ketchum 01.cbz
		Black Jack Ketchum 02.cbz
	Cognetic	
		Cognetic (1 of 3).cbz
		Cognetic (2 of 3).cbz
		Cognetic (3 of 3).cbz
	Faster than Light	
		Faster than Light 01.cbz
		Faster than Light 02.cbz
		Faster than Light 03.cbz
		Faster than Light 04.cbz
		Faster than Light 05.cbz
	From Under Mountains	
		From Under Mountains 01.cbz
		From Under Mountains 02.cbz
		From Under Mountains 03.cbz
		From Under Mountains 04.cbz
	John Flood
		John Flood (1 of 6).cbz
		John Flood (2 of 6).cbz
		John Flood (3 of 6).cbz
		John Flood (4 of 6).cbz
		John Flood (5 of 6).cbz
		John Flood (6 of 6).cbz
	Limbo	
		Limbo 01.cbz
		Limbo 02.cbz
		Limbo 03.cbz
	No Mercy
		No Mercy 01.cbz
		No Mercy 02.cbz
		No Mercy 03.cbz
		No Mercy 04.cbz
		No Mercy 05.cbz
		No Mercy 06.cbz
	Slash & Burn
		Slash & Burn 01.cbz
		Slash & Burn 02.cbz
		Slash & Burn 03.cbz
	Spread	
		Spread 09.cbz
		Spread 10.cbz
		Spread 11.cbz
		Spread 12.cbz
	The Violent
		The Violent 01.cbz
		The Violent 02.cbz
	Kaptara vol.1 Fear Not, Tiny Alien TPB.cbz
	Wayward: Deluxe Book 1 TPB.cbz
	Wolf: Blood and Magic TPB.cbz

Pow! shows both folders and single files (trade paperbacks) in the same window.

**Comment by nkanaev** [comment]
ok, i've implemented showing relative directory structure if the directory is nested. the feature will be part of the next release
