### ISSUE TITLE
Blank screen with small images

### ISSUE THREAD

**Issue by edent** [nkanaev/bubble#28]
Some comics have images with small dimensions.  These images show as blank screens in Bubble.  Larger images within the same comic display normally.

I've tried Aspect Fill, Aspect Fit, and Fit Width - but the pages remain blank.

Here is a sample comic which displays the problem. Images 1 & 4 display normally, images 2 & 3 just show as black screen.
[xkcd.cbz.zip](https://github.com/nkanaev/bubble/files/149374/xkcd.cbz.zip)
(Using [Creative Commons XKCD](http://xkcd.com/license.html) )

Using Bubble 1.4.0(5) from F-Droid.

**Comment by nkanaev** [comment]
thanks for the report. I guess the issue was related to a buggy image resizing, which has been fixed. patch will be available in the next release
