### ISSUE TITLE
[Feature Request] Beter view panel

### ISSUE THREAD

**Issue by droidberg** [nkanaev/bubble#29]
hey nkanaev, thanks for your continued hard work on bubble! it really saddens me that your app is not as widespread as others but im trying. also, thanks for keeping it to local storage and not cloud. so, currently you have bubble set up to switch from unread, read and reading set as a multiple choice from a button. is there any way you can switch that to left panel for easier acess? i have included a mockup for better explaining. also, how about a donate button? im happy that your providing your work for free but i and im sure many others would like to help you keep it that way.

http://i.imgur.com/YJnJr5R.jpg

**Comment by nkanaev** [comment]
sorry, I think the current design is sufficient to provide the needed reading experience. As each users' taste is different, there is no absolute solution for the ui.
