### ISSUE TITLE
Remove non free/libre unrar library

### ISSUE THREAD

**Issue by RyDroid** [nkanaev/bubble#3]
At least, version 1.1 uses [unrar library](https://github.com/junrar/junrar/blob/master/license.txt) (see "About" part of the app). But it is proprietary, that is why [it is in non-free in Debian](https://packages.debian.org/sid/unrar). So the app is not fully free/libre.
So I think that unrar should be removed or replaced by [unrar-free](https://packages.debian.org/sid/unrar-free). Another solution could be creating a git branch without it or a compilation option.
Regards.

**Comment by nkanaev** [comment]
Application uses [junrar](https://github.com/edmund-wagner/junrar/tree/master/unrar), open-source implementation of rar archive. But as you might know, rar decompression code is copyright (c) by Eugene Roshal. The only reason why I added the latter license is that junrar author did not specify his own license.

**Comment by RyDroid** [comment]
* In the app, the link goes to [junrar/junrar](https://github.com/junrar/junrar). In your comment, the link goes to [edmund-wagner/junrar](https://github.com/edmund-wagner/junrar/tree/master/unrar).
* In both repo, there is the same [copyright file](https://github.com/junrar/junrar/blob/master/license.txt) as in [unrar of non-free of Debian](http://metadata.ftp-master.debian.org/changelogs/non-free/u/unrar-nonfree/unrar-nonfree_5.3.2-1_copyright). [Fedora does not like this license too](https://fedoraproject.org/wiki/Licensing:Unrar).
* "The UnRAR sources may be used in any software to handle RAR archives without limitations free of charge, **but cannot be used to re-create the RAR compression algorithm**" "**the code may not be used to develop a RAR (WinRAR) compatible archiver**"
   * [Open Source](http://opensource.org/osd) : (section 4) "The license must explicitly permit distribution of software built from modified source code." This license may also violate section 8.
   * [Free Software](https://www.gnu.org/philosophy/free-sw.en.html) : "If your right to modify a program is limited, in substance, to changes that someone else considers an improvement, that program is not free."
* Even if MS add copyright on Windows, it does not allow him to forbid to create free/libre and open source implementations like WINE and ReactOS. The only country that I know were MS could attack WINE and ReactOS is [USA (see Google vs Oracle)](https://www.eff.org/cases/oracle-v-google). So it is the same for compressing RAR, source code by Eugene Roshal just must not be used.
* There is a free/libre decompression implementation of RAR (version format prior to 3.0). https://gna.org/projects/unrar/ https://packages.debian.org/sid/unrar-free

**Comment by nkanaev** [comment]
`junrar/junrar` is the fork of `edmund-wagner/junrar` (which adds maven support). `Junrar` IS a free implementation of RAR archive (just like `unrar-free`), but without copyright notice of the original author. If the author adds his own license, I'll change the link.
