### ISSUE TITLE
cbt/tarball support

### ISSUE THREAD

**Issue by jiminorris** [nkanaev/bubble#32]
Bubble doesn't see to support opening comic archives in cbt (tarball) format

**Comment by jiminorris** [comment]
Note, the CBT files I have are archived webp images, so if cbt files are supported, and I've missed it, I'll open another issue for webp files.

**Comment by nkanaev** [comment]
CBT archives currently are not supported (will be added in the next release). Android 4.0+ supports webp media format, so no need to open the issue.

**Comment by droidberg** [comment]
hello nkanaev, while android does support webp it seems that bubble doesnt like it very much. i tried both a cbz and cbr file with webp images. none of them showed up in bubble. another comic viewer was able to open them. is this a bug or a problem on my device?

**Comment by nkanaev** [comment]
seems like a bug. will have a look

**Comment by nkanaev** [comment]
added cbt support. will be in the next release
