### ISSUE TITLE
Double Tap to Zoom

### ISSUE THREAD

**Issue by droidberg** [nkanaev/bubble#34]
hello nkanaev. thanks for the recent update. the latest tap to zoom works great at returning the zoomed page back to normal but it has a flaw. when you double tap the page zooms to an extreme point. instead could you rather zoom to page height? since bubble currently shows pages zoomed to width, double tapping should zoom to image height and if a user needs more zoom they can just pinch.

**Comment by nkanaev** [comment]
double tap zooms to max level. custom zoom level can be achieved with pinch zoom.
