### ISSUE TITLE
[Bug Report] webp not showing

### ISSUE THREAD

**Issue by droidberg** [nkanaev/bubble#36]
hey nkanaev, i know you commented on another post about looking into the webp problem. so far bubble fails to see the files. thanks in advance.

**Comment by nkanaev** [comment]
yes, this is my fault. will be fixed in the next release

**Comment by droidberg** [comment]
i apologize for the pestering nkanaev. i just started converting my comics to webp so as to save storage space and without bubble there is no point. thanks nkanaev!

**Comment by nkanaev** [comment]
fixed. will be part of the next release
