### ISSUE TITLE
Zoom back in after zooming out too much

### ISSUE THREAD

**Issue by frandavid100** [nkanaev/bubble#37]
If you zoom out too much, in a way that the image only uses part of the screen, it stays like this:

![screenshot_20160707-090030](https://cloud.githubusercontent.com/assets/694794/16645152/3a72f956-4422-11e6-8a0c-6c6bf2798607.png)

Would it be possible to make it "bounce" back, so that it automatically zooms it until it fills the screen?

**Comment by nkanaev** [comment]
unfortunately, no. this is done on purpose. but you can double-click image to restore the original size.
