### ISSUE TITLE
Open Bubble when clicking a CBR file from a file manager

### ISSUE THREAD

**Issue by frandavid100** [nkanaev/bubble#38]
Hi,

Whenever I download a CBR file and click on it, I get an error message that the file couldn't be opened. Woul it be possible to get the option to open it on Bubble straight away?

Thanks!

**Comment by nkanaev** [comment]
1. which version of the app is installed?
2. what file manager are you using?

**Comment by nkanaev** [comment]
hopefully fixed now. will be available in the next release

**Comment by frandavid100** [comment]
Awesome, I'll confirm when the update hits.
