### ISSUE TITLE
Feature request: open next comic at the end of a comic

### ISSUE THREAD

**Issue by IceHand84** [nkanaev/bubble#4]
Do you accept feature requests? If you do: I would love the possibility to open the next comic at the end of a comic without going into library view. One possibilty would be next/previous comic buttons. Another would be that a message pops up when you press page turn at the end of a comic e.g. "Press page turn again to open $next-comic".

**Comment by nkanaev** [comment]
Nice feature. Will be implemented in the upcoming release.

**Comment by IceHand84** [comment]
Nice, thank you!

**Comment by nkanaev** [comment]
Implemented in v1.2.0
