### ISSUE TITLE
Distinction between unread, read and currently reading

### ISSUE THREAD

**Issue by IceHand84** [nkanaev/bubble#5]
Right now Bubble sees unopened comics as "unread" and once you open a comic as "read" -- no matter what page you're on. I would love to see a "currently reading" state. My suggestion would be:
- Unread: comic never opened (just as it is now)
- Currently reading: comic opened, but not on the last page
- Read: comic opened and on the last page (you could add a small checkmark next to the page counter (e.g. 42/42✓) in library view to make it clear that it counts as read)

If you implement this, it would be nice to have the option to long-press a comic in library view to select one or more comics an then show buttons to "Mark as read/unread" and maybe even "Delete".

An optional but nice feature would be a "Currently reading" virtual folder at the top in library view where all comics from your library are listed that have the appropriate state.

EDIT: Sorry, I forgot to make my main point: I would like to be able to filter "finished" (read) and "unfinished" (unread+currently reading) comics. The other stuff would be nice but optional.

**Comment by nkanaev** [comment]
Implemented in v1.2.0: made a distinction between "read" and "currently reading" (previously was only "read")
