### ISSUE TITLE
[improvement] Refresh library view on startup

### ISSUE THREAD

**Issue by RyDroid** [nkanaev/bubble#6]
I added a new chapter to one of my collections of manga, but it did not appeared. I was forced to reselect the directory, so that it again looked in it to find the new chapter.
An option to search for new and missing folder on startup would be nice. It would be better to do it asynchronously, in order to browse our collection and having the new folder that pops, otherwise we would have to wait that the search is finished before browsing.
Regards.

**Comment by nkanaev** [comment]
Currently refreshing can be done by using "swipe down to refresh" on the library view. As of auto-refresh capability - I might implement it in the near future.

**Comment by nkanaev** [comment]
done. the library will auto-refresh on the app start
