### ISSUE TITLE
[improvement] Use the first image for the card of "final" directories

### ISSUE THREAD

**Issue by RyDroid** [nkanaev/bubble#7]
All cards (the white rectangle with the name of the folder) are currently blanks. We can assume that a "final" directory (a directory that does not contain one or more directories) is a chapter. Usually a chapter starts with a front page that is the first image in the directory. So it would be nice to use the first image of a final directory for the corresponding card.
Regards.

**Comment by nkanaev** [comment]
Implemented in v1.2.0
